# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI_user.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1233, 757)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 710))
        MainWindow.setMaximumSize(QtCore.QSize(14400, 9000))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setIconSize(QtCore.QSize(50, 50))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(3, -1, 3, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_OpenFile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_OpenFile.setEnabled(True)
        self.pushButton_OpenFile.setMinimumSize(QtCore.QSize(65, 65))
        self.pushButton_OpenFile.setMaximumSize(QtCore.QSize(65, 65))
        self.pushButton_OpenFile.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pic/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_OpenFile.setIcon(icon1)
        self.pushButton_OpenFile.setIconSize(QtCore.QSize(65, 65))
        self.pushButton_OpenFile.setObjectName("pushButton_OpenFile")
        self.verticalLayout.addWidget(self.pushButton_OpenFile)
        self.label_p1 = QtWidgets.QLabel(self.centralwidget)
        self.label_p1.setMinimumSize(QtCore.QSize(0, 0))
        self.label_p1.setMaximumSize(QtCore.QSize(65, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_p1.setFont(font)
        self.label_p1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_p1.setAutoFillBackground(False)
        self.label_p1.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_p1.setObjectName("label_p1")
        self.verticalLayout.addWidget(self.label_p1)
        self.pushButton_SendFile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_SendFile.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SendFile.sizePolicy().hasHeightForWidth())
        self.pushButton_SendFile.setSizePolicy(sizePolicy)
        self.pushButton_SendFile.setMinimumSize(QtCore.QSize(65, 65))
        self.pushButton_SendFile.setMaximumSize(QtCore.QSize(65, 65))
        self.pushButton_SendFile.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pic/send.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_SendFile.setIcon(icon2)
        self.pushButton_SendFile.setIconSize(QtCore.QSize(65, 65))
        self.pushButton_SendFile.setAutoDefault(False)
        self.pushButton_SendFile.setDefault(False)
        self.pushButton_SendFile.setFlat(False)
        self.pushButton_SendFile.setObjectName("pushButton_SendFile")
        self.verticalLayout.addWidget(self.pushButton_SendFile)
        self.label_p2 = QtWidgets.QLabel(self.centralwidget)
        self.label_p2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_p2.setMaximumSize(QtCore.QSize(65, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_p2.setFont(font)
        self.label_p2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_p2.setObjectName("label_p2")
        self.verticalLayout.addWidget(self.label_p2)
        self.pushButton_ReceiveFile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ReceiveFile.setEnabled(False)
        self.pushButton_ReceiveFile.setMinimumSize(QtCore.QSize(65, 65))
        self.pushButton_ReceiveFile.setMaximumSize(QtCore.QSize(65, 65))
        self.pushButton_ReceiveFile.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/pic/receive.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ReceiveFile.setIcon(icon3)
        self.pushButton_ReceiveFile.setIconSize(QtCore.QSize(65, 65))
        self.pushButton_ReceiveFile.setObjectName("pushButton_ReceiveFile")
        self.verticalLayout.addWidget(self.pushButton_ReceiveFile)
        self.label_p3 = QtWidgets.QLabel(self.centralwidget)
        self.label_p3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_p3.setMaximumSize(QtCore.QSize(65, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_p3.setFont(font)
        self.label_p3.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_p3.setObjectName("label_p3")
        self.verticalLayout.addWidget(self.label_p3)
        self.pushButton_OpenFeedback = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_OpenFeedback.setEnabled(False)
        self.pushButton_OpenFeedback.setMinimumSize(QtCore.QSize(65, 65))
        self.pushButton_OpenFeedback.setMaximumSize(QtCore.QSize(65, 65))
        self.pushButton_OpenFeedback.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/pic/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_OpenFeedback.setIcon(icon4)
        self.pushButton_OpenFeedback.setIconSize(QtCore.QSize(65, 65))
        self.pushButton_OpenFeedback.setObjectName("pushButton_OpenFeedback")
        self.verticalLayout.addWidget(self.pushButton_OpenFeedback)
        self.label_p4 = QtWidgets.QLabel(self.centralwidget)
        self.label_p4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_p4.setMaximumSize(QtCore.QSize(65, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_p4.setFont(font)
        self.label_p4.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_p4.setObjectName("label_p4")
        self.verticalLayout.addWidget(self.label_p4)
        self.pushButton_Concel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Concel.setEnabled(False)
        self.pushButton_Concel.setMinimumSize(QtCore.QSize(65, 65))
        self.pushButton_Concel.setMaximumSize(QtCore.QSize(65, 65))
        self.pushButton_Concel.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/pic/concel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Concel.setIcon(icon5)
        self.pushButton_Concel.setIconSize(QtCore.QSize(65, 65))
        self.pushButton_Concel.setObjectName("pushButton_Concel")
        self.verticalLayout.addWidget(self.pushButton_Concel)
        self.label_p5 = QtWidgets.QLabel(self.centralwidget)
        self.label_p5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_p5.setMaximumSize(QtCore.QSize(65, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_p5.setFont(font)
        self.label_p5.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_p5.setObjectName("label_p5")
        self.verticalLayout.addWidget(self.label_p5)
        self.pushButton_Delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Delete.setEnabled(False)
        self.pushButton_Delete.setMinimumSize(QtCore.QSize(65, 65))
        self.pushButton_Delete.setMaximumSize(QtCore.QSize(65, 65))
        self.pushButton_Delete.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/pic/del.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Delete.setIcon(icon6)
        self.pushButton_Delete.setIconSize(QtCore.QSize(65, 65))
        self.pushButton_Delete.setObjectName("pushButton_Delete")
        self.verticalLayout.addWidget(self.pushButton_Delete)
        self.label_p6 = QtWidgets.QLabel(self.centralwidget)
        self.label_p6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_p6.setMaximumSize(QtCore.QSize(65, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_p6.setFont(font)
        self.label_p6.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_p6.setObjectName("label_p6")
        self.verticalLayout.addWidget(self.label_p6)
        self.pushButton_Search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Search.setMinimumSize(QtCore.QSize(65, 65))
        self.pushButton_Search.setMaximumSize(QtCore.QSize(65, 65))
        self.pushButton_Search.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/pic/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Search.setIcon(icon7)
        self.pushButton_Search.setIconSize(QtCore.QSize(65, 65))
        self.pushButton_Search.setObjectName("pushButton_Search")
        self.verticalLayout.addWidget(self.pushButton_Search)
        self.label_p7 = QtWidgets.QLabel(self.centralwidget)
        self.label_p7.setMaximumSize(QtCore.QSize(65, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_p7.setFont(font)
        self.label_p7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_p7.setObjectName("label_p7")
        self.verticalLayout.addWidget(self.label_p7)
        self.pushButton_Wechat = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Wechat.setMinimumSize(QtCore.QSize(65, 65))
        self.pushButton_Wechat.setMaximumSize(QtCore.QSize(65, 65))
        self.pushButton_Wechat.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/pic/wechat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Wechat.setIcon(icon8)
        self.pushButton_Wechat.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_Wechat.setObjectName("pushButton_Wechat")
        self.verticalLayout.addWidget(self.pushButton_Wechat)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 2, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 1, 2, 2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.l1 = QtWidgets.QLabel(self.centralwidget)
        self.l1.setMinimumSize(QtCore.QSize(68, 0))
        self.l1.setMaximumSize(QtCore.QSize(68, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l1.setFont(font)
        self.l1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l1.setAlignment(QtCore.Qt.AlignCenter)
        self.l1.setObjectName("l1")
        self.horizontalLayout_3.addWidget(self.l1)
        self.LineEdit_AskFileName = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit_AskFileName.setMinimumSize(QtCore.QSize(0, 25))
        self.LineEdit_AskFileName.setAcceptDrops(False)
        self.LineEdit_AskFileName.setReadOnly(True)
        self.LineEdit_AskFileName.setObjectName("LineEdit_AskFileName")
        self.horizontalLayout_3.addWidget(self.LineEdit_AskFileName)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.l2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l2.sizePolicy().hasHeightForWidth())
        self.l2.setSizePolicy(sizePolicy)
        self.l2.setMinimumSize(QtCore.QSize(68, 0))
        self.l2.setMaximumSize(QtCore.QSize(68, 16777215))
        self.l2.setSizeIncrement(QtCore.QSize(64, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l2.setFont(font)
        self.l2.setAlignment(QtCore.Qt.AlignCenter)
        self.l2.setObjectName("l2")
        self.horizontalLayout_6.addWidget(self.l2)
        self.LineEdit_FileID = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit_FileID.setMinimumSize(QtCore.QSize(0, 25))
        self.LineEdit_FileID.setMaximumSize(QtCore.QSize(8000, 16777215))
        self.LineEdit_FileID.setSizeIncrement(QtCore.QSize(400, 0))
        self.LineEdit_FileID.setReadOnly(True)
        self.LineEdit_FileID.setObjectName("LineEdit_FileID")
        self.horizontalLayout_6.addWidget(self.LineEdit_FileID)
        self.l3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l3.sizePolicy().hasHeightForWidth())
        self.l3.setSizePolicy(sizePolicy)
        self.l3.setMinimumSize(QtCore.QSize(68, 0))
        self.l3.setMaximumSize(QtCore.QSize(68, 16777215))
        self.l3.setSizeIncrement(QtCore.QSize(64, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l3.setFont(font)
        self.l3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l3.setAlignment(QtCore.Qt.AlignCenter)
        self.l3.setObjectName("l3")
        self.horizontalLayout_6.addWidget(self.l3)
        self.LineEdit_StartTime = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit_StartTime.setEnabled(True)
        self.LineEdit_StartTime.setMinimumSize(QtCore.QSize(0, 25))
        self.LineEdit_StartTime.setMaximumSize(QtCore.QSize(5000, 16777215))
        self.LineEdit_StartTime.setSizeIncrement(QtCore.QSize(218, 0))
        self.LineEdit_StartTime.setAcceptDrops(False)
        self.LineEdit_StartTime.setReadOnly(True)
        self.LineEdit_StartTime.setObjectName("LineEdit_StartTime")
        self.horizontalLayout_6.addWidget(self.LineEdit_StartTime)
        self.l4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l4.sizePolicy().hasHeightForWidth())
        self.l4.setSizePolicy(sizePolicy)
        self.l4.setMinimumSize(QtCore.QSize(68, 0))
        self.l4.setMaximumSize(QtCore.QSize(68, 16777215))
        self.l4.setSizeIncrement(QtCore.QSize(64, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l4.setFont(font)
        self.l4.setAlignment(QtCore.Qt.AlignCenter)
        self.l4.setObjectName("l4")
        self.horizontalLayout_6.addWidget(self.l4)
        self.LineEdit_SendSw = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit_SendSw.setMinimumSize(QtCore.QSize(0, 25))
        self.LineEdit_SendSw.setMaximumSize(QtCore.QSize(1500, 16777215))
        self.LineEdit_SendSw.setSizeIncrement(QtCore.QSize(148, 0))
        self.LineEdit_SendSw.setReadOnly(True)
        self.LineEdit_SendSw.setObjectName("LineEdit_SendSw")
        self.horizontalLayout_6.addWidget(self.LineEdit_SendSw)
        self.horizontalLayout_6.setStretch(1, 3)
        self.horizontalLayout_6.setStretch(2, 1)
        self.horizontalLayout_6.setStretch(3, 2)
        self.horizontalLayout_6.setStretch(4, 1)
        self.horizontalLayout_6.setStretch(5, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.l5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l5.sizePolicy().hasHeightForWidth())
        self.l5.setSizePolicy(sizePolicy)
        self.l5.setMinimumSize(QtCore.QSize(68, 0))
        self.l5.setMaximumSize(QtCore.QSize(68, 16777215))
        self.l5.setSizeIncrement(QtCore.QSize(64, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l5.setFont(font)
        self.l5.setAlignment(QtCore.Qt.AlignCenter)
        self.l5.setObjectName("l5")
        self.horizontalLayout_2.addWidget(self.l5)
        self.LineEdit_FeedbackFile = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit_FeedbackFile.setMinimumSize(QtCore.QSize(0, 25))
        self.LineEdit_FeedbackFile.setMaximumSize(QtCore.QSize(8000, 16777215))
        self.LineEdit_FeedbackFile.setSizeIncrement(QtCore.QSize(0, 0))
        self.LineEdit_FeedbackFile.setAcceptDrops(False)
        self.LineEdit_FeedbackFile.setReadOnly(True)
        self.LineEdit_FeedbackFile.setObjectName("LineEdit_FeedbackFile")
        self.horizontalLayout_2.addWidget(self.LineEdit_FeedbackFile)
        self.l6 = QtWidgets.QLabel(self.centralwidget)
        self.l6.setMinimumSize(QtCore.QSize(68, 0))
        self.l6.setMaximumSize(QtCore.QSize(68, 16777215))
        self.l6.setSizeIncrement(QtCore.QSize(64, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l6.setFont(font)
        self.l6.setAlignment(QtCore.Qt.AlignCenter)
        self.l6.setObjectName("l6")
        self.horizontalLayout_2.addWidget(self.l6)
        self.LineEdit_FeedbackTime = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit_FeedbackTime.setMinimumSize(QtCore.QSize(0, 25))
        self.LineEdit_FeedbackTime.setMaximumSize(QtCore.QSize(5000, 16777215))
        self.LineEdit_FeedbackTime.setSizeIncrement(QtCore.QSize(218, 0))
        self.LineEdit_FeedbackTime.setAcceptDrops(False)
        self.LineEdit_FeedbackTime.setReadOnly(True)
        self.LineEdit_FeedbackTime.setObjectName("LineEdit_FeedbackTime")
        self.horizontalLayout_2.addWidget(self.LineEdit_FeedbackTime)
        self.l7 = QtWidgets.QLabel(self.centralwidget)
        self.l7.setMinimumSize(QtCore.QSize(68, 0))
        self.l7.setMaximumSize(QtCore.QSize(68, 16777215))
        self.l7.setSizeIncrement(QtCore.QSize(64, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l7.setFont(font)
        self.l7.setAlignment(QtCore.Qt.AlignCenter)
        self.l7.setObjectName("l7")
        self.horizontalLayout_2.addWidget(self.l7)
        self.LineEdit_FeedbackStatus = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit_FeedbackStatus.setMinimumSize(QtCore.QSize(0, 25))
        self.LineEdit_FeedbackStatus.setMaximumSize(QtCore.QSize(1500, 16777215))
        self.LineEdit_FeedbackStatus.setSizeIncrement(QtCore.QSize(148, 0))
        self.LineEdit_FeedbackStatus.setReadOnly(True)
        self.LineEdit_FeedbackStatus.setObjectName("LineEdit_FeedbackStatus")
        self.horizontalLayout_2.addWidget(self.LineEdit_FeedbackStatus)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(3, 2)
        self.horizontalLayout_2.setStretch(4, 1)
        self.horizontalLayout_2.setStretch(5, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.l8 = QtWidgets.QLabel(self.centralwidget)
        self.l8.setMinimumSize(QtCore.QSize(68, 0))
        self.l8.setMaximumSize(QtCore.QSize(68, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l8.setFont(font)
        self.l8.setAlignment(QtCore.Qt.AlignCenter)
        self.l8.setObjectName("l8")
        self.horizontalLayout_5.addWidget(self.l8)
        self.LineEdit_User = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit_User.setMinimumSize(QtCore.QSize(150, 25))
        self.LineEdit_User.setReadOnly(True)
        self.LineEdit_User.setObjectName("LineEdit_User")
        self.horizontalLayout_5.addWidget(self.LineEdit_User)
        self.l9 = QtWidgets.QLabel(self.centralwidget)
        self.l9.setMinimumSize(QtCore.QSize(68, 0))
        self.l9.setMaximumSize(QtCore.QSize(68, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l9.setFont(font)
        self.l9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l9.setAlignment(QtCore.Qt.AlignCenter)
        self.l9.setObjectName("l9")
        self.horizontalLayout_5.addWidget(self.l9)
        self.LineEdit_What = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit_What.setMinimumSize(QtCore.QSize(98, 25))
        self.LineEdit_What.setReadOnly(True)
        self.LineEdit_What.setObjectName("LineEdit_What")
        self.horizontalLayout_5.addWidget(self.LineEdit_What)
        self.l10 = QtWidgets.QLabel(self.centralwidget)
        self.l10.setMinimumSize(QtCore.QSize(68, 0))
        self.l10.setMaximumSize(QtCore.QSize(68, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l10.setFont(font)
        self.l10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l10.setAlignment(QtCore.Qt.AlignCenter)
        self.l10.setObjectName("l10")
        self.horizontalLayout_5.addWidget(self.l10)
        self.LineEdit_Who = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit_Who.setMinimumSize(QtCore.QSize(160, 25))
        self.LineEdit_Who.setReadOnly(True)
        self.LineEdit_Who.setObjectName("LineEdit_Who")
        self.horizontalLayout_5.addWidget(self.LineEdit_Who)
        self.l11 = QtWidgets.QLabel(self.centralwidget)
        self.l11.setMinimumSize(QtCore.QSize(68, 0))
        self.l11.setMaximumSize(QtCore.QSize(68, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l11.setFont(font)
        self.l11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l11.setAlignment(QtCore.Qt.AlignCenter)
        self.l11.setObjectName("l11")
        self.horizontalLayout_5.addWidget(self.l11)
        self.LineEdit_PersonNum = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit_PersonNum.setMinimumSize(QtCore.QSize(100, 25))
        self.LineEdit_PersonNum.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineEdit_PersonNum.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.LineEdit_PersonNum.setReadOnly(True)
        self.LineEdit_PersonNum.setObjectName("LineEdit_PersonNum")
        self.horizontalLayout_5.addWidget(self.LineEdit_PersonNum)
        self.l12 = QtWidgets.QLabel(self.centralwidget)
        self.l12.setMinimumSize(QtCore.QSize(68, 0))
        self.l12.setMaximumSize(QtCore.QSize(68, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l12.setFont(font)
        self.l12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l12.setAlignment(QtCore.Qt.AlignCenter)
        self.l12.setObjectName("l12")
        self.horizontalLayout_5.addWidget(self.l12)
        self.LineEdit_UnitNum = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_UnitNum.sizePolicy().hasHeightForWidth())
        self.LineEdit_UnitNum.setSizePolicy(sizePolicy)
        self.LineEdit_UnitNum.setMinimumSize(QtCore.QSize(100, 25))
        self.LineEdit_UnitNum.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineEdit_UnitNum.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.LineEdit_UnitNum.setReadOnly(True)
        self.LineEdit_UnitNum.setObjectName("LineEdit_UnitNum")
        self.horizontalLayout_5.addWidget(self.LineEdit_UnitNum)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(68, 0))
        self.label.setMaximumSize(QtCore.QSize(68, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.textBrowser_BankInfo = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_BankInfo.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textBrowser_BankInfo.setFont(font)
        self.textBrowser_BankInfo.setObjectName("textBrowser_BankInfo")
        self.horizontalLayout.addWidget(self.textBrowser_BankInfo)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableView_Data = QtWidgets.QTableView(self.centralwidget)
        self.tableView_Data.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableView_Data.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableView_Data.setMidLineWidth(1)
        self.tableView_Data.setObjectName("tableView_Data")
        self.verticalLayout_2.addWidget(self.tableView_Data)
        self.textBrowser_Info = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_Info.setStyleSheet("font-size:15px; background:#696969")
        self.textBrowser_Info.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowser_Info.setMaximumSize(QtCore.QSize(20000, 20000))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textBrowser_Info.setFont(font)
        self.textBrowser_Info.setObjectName("textBrowser_Info")
        self.verticalLayout_2.addWidget(self.textBrowser_Info)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(2, 1)
        self.verticalLayout_3.setStretch(3, 1)
        self.verticalLayout_3.setStretch(4, 2)
        self.verticalLayout_3.setStretch(5, 15)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionedit = QtWidgets.QAction(MainWindow)
        self.actionedit.setObjectName("actionedit")
        self.actionfile_open = QtWidgets.QAction(MainWindow)
        self.actionfile_open.setObjectName("actionfile_open")
        self.actionFind = QtWidgets.QAction(MainWindow)
        self.actionFind.setObjectName("actionFind")
        # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>
        # tip for send
        self.lineEdit_Tip_send = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Tip_send.setEnabled(True)
        self.lineEdit_Tip_send.setAcceptDrops(False)
        self.lineEdit_Tip_send.setReadOnly(True)
        self.lineEdit_Tip_send.setObjectName("lineEdit_Tip_send")
        self.lineEdit_Tip_send.setAlignment(Qt.AlignCenter | Qt.AlignVCenter)
        self.lineEdit_Tip_send.setStyleSheet("color:#ffffff;font-size:16px; border-radius:10px; background:#FF4500;"
                                             "border-width:0")
        self.lineEdit_Tip_send.setVisible(False)

        # tip for receive
        self.lineEdit_Tip_receive = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Tip_receive.setEnabled(True)
        self.lineEdit_Tip_receive.setAcceptDrops(False)
        self.lineEdit_Tip_receive.setReadOnly(True)
        self.lineEdit_Tip_receive.setObjectName("lineEdit_Tip_receive")
        self.lineEdit_Tip_receive.setAlignment(Qt.AlignCenter | Qt.AlignVCenter)
        self.lineEdit_Tip_receive.setStyleSheet("color:#ffffff;font-size:16px; border-radius:10px; background:#FF4500;"
                                                "border-width:0")
        self.lineEdit_Tip_receive.setVisible(False)

        # tip for login

        # 》》》》》》》》》》》》》》》》》》》》》》》》
        self.Frame = QtWidgets.QWidget(MainWindow)
        self.Frame.setStyleSheet("background:#F0F0F0")
        self.Frame.setObjectName("Frame")
        self.Frame.resize(975, 38)
        self.Frame.setMinimumSize(QtCore.QSize(900, 38))
        self.Frame.setMaximumSize(QtCore.QSize(19600, 38))
        #   self.Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        #  self.Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 661, 38))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_22 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout.addWidget(self.label_22)
        self.comboBox_area = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_area.setStyleSheet("border-style:solid;border-width:1px")
        # self.comboBox_area.setStyleSheet("QComboBox::drop-down{border-width:1px}")
        self.comboBox_area.setMinimumSize(QtCore.QSize(140, 25))
        self.comboBox_area.setMaximumSize(QtCore.QSize(140, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.comboBox_area.setFont(font)
        self.comboBox_area.setObjectName("comboBox_area")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_area)
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout.addWidget(self.label_21)
        self.lineEdit_keyword = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_keyword.setMinimumSize(QtCore.QSize(200, 25))
        self.lineEdit_keyword.setMaximumSize(QtCore.QSize(200, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.lineEdit_keyword.setFont(font)
        self.lineEdit_keyword.setObjectName("lineEdit_keyword")
        self.horizontalLayout.addWidget(self.lineEdit_keyword)

        self.pushButton_Backward = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_Backward.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_Backward.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_Backward.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/back.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pushButton_Backward.setIcon(icon)
        self.pushButton_Backward.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_Backward.setFlat(True)
        self.pushButton_Backward.setObjectName("pushButton_Backward")
        self.horizontalLayout.addWidget(self.pushButton_Backward)

        self.pushButton_Find = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_Find.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_Find.setSizeIncrement(QtCore.QSize(35, 35))
        self.pushButton_Find.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pic/search2.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pushButton_Find.setIcon(icon1)
        self.pushButton_Find.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_Find.setFlat(True)
        self.pushButton_Find.setObjectName("pushButton_Find")
        self.horizontalLayout.addWidget(self.pushButton_Find)

        self.pushButton_Forward = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_Forward.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_Forward.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_Forward.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pic/next.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pushButton_Forward.setIcon(icon2)
        self.pushButton_Forward.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_Forward.setFlat(True)
        self.pushButton_Forward.setObjectName("pushButton_Forward")
        self.horizontalLayout.addWidget(self.pushButton_Forward)

        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.Frame.hide()
        # 》》》》》》》》》》》》》》》》》》》》》》》》

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "协查文书传输系统（纪委监委）"))
        self.label_p1.setText(_translate("MainWindow", "添加查询"))
        self.label_p2.setText(_translate("MainWindow", "发送查询"))
        self.label_p3.setText(_translate("MainWindow", "接收反馈"))
        self.label_p4.setText(_translate("MainWindow", "打开反馈"))
        self.label_p5.setText(_translate("MainWindow", "撤销查询"))
        self.label_p6.setText(_translate("MainWindow", "删除查询"))
        self.label_p7.setText(_translate("MainWindow", "查询记录"))
        self.l1.setText(_translate("MainWindow", "查询文书"))
        self.l2.setText(_translate("MainWindow", "查询编号"))
        self.l3.setText(_translate("MainWindow", "发起时间"))
        self.l4.setText(_translate("MainWindow", "发送状态"))
        self.l5.setText(_translate("MainWindow", "反馈编号"))
        self.l6.setText(_translate("MainWindow", "反馈时间"))
        self.l7.setText(_translate("MainWindow", "反馈状态"))
        self.l8.setText(_translate("MainWindow", "申请单位"))
        self.l9.setText(_translate("MainWindow", "协查内容"))
        self.l10.setText(_translate("MainWindow", "对象名称"))
        self.l11.setText(_translate("MainWindow", "人    数"))
        self.l12.setText(_translate("MainWindow", "单 位 数"))
        self.label.setText(_translate("MainWindow", "附加信息"))
        self.actionedit.setText(_translate("MainWindow", "Open File"))
        self.actionfile_open.setText(_translate("MainWindow", "Open file..."))
        self.actionFind.setText(_translate("MainWindow", "Find..."))


        self.label_22.setText(_translate("Frame", "查询范围"))
        self.comboBox_area.setItemText(0, _translate("Frame", "查询文件编号"))
        self.comboBox_area.setItemText(1, _translate("Frame", "查询文件名称"))
        self.comboBox_area.setItemText(2, _translate("Frame", "查询时间"))
        self.comboBox_area.setItemText(3, _translate("Frame", "申请单位"))
        self.comboBox_area.setItemText(4, _translate("Frame", "对象名称"))
        self.comboBox_area.setItemText(5, _translate("Frame", "反馈时间"))
        self.comboBox_area.setItemText(6, _translate("Frame", "反馈文件名称"))
        self.label_21.setText(_translate("Frame", "关键字"))

        self.label.setText(_translate("MainWindow", "查询结果"))
        self.actionedit.setText(_translate("MainWindow", "Open File"))
        self.actionfile_open.setText(_translate("MainWindow", "Open file..."))
        self.actionFind.setText(_translate("MainWindow", "Find..."))
import JW_rc
