# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changenameUI_user.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import json

class Ui_Dialog_ChangeFileName(object):
    def setupUi(self, Dialog_ChangeFileName):
        Dialog_ChangeFileName.setObjectName("Dialog_ChangeFileName")
        Dialog_ChangeFileName.setWindowModality(QtCore.Qt.NonModal)
        Dialog_ChangeFileName.resize(800, 880)
        Dialog_ChangeFileName.setMinimumSize(QtCore.QSize(800, 880))
        Dialog_ChangeFileName.setMaximumSize(QtCore.QSize(800, 880))
        Dialog_ChangeFileName.setToolTipDuration(0)
        self.widget = QtWidgets.QWidget(Dialog_ChangeFileName)
        self.widget.setGeometry(QtCore.QRect(11, 235, 781, 631))
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_FindBank = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_FindBank.setMinimumSize(QtCore.QSize(0, 48))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.lineEdit_FindBank.setFont(font)
        self.lineEdit_FindBank.setObjectName("lineEdit_FindBank")
        self.verticalLayout_3.addWidget(self.lineEdit_FindBank)
        self.listView_BankList = QtWidgets.QListView(self.widget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.listView_BankList.setFont(font)
        self.listView_BankList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView_BankList.setAlternatingRowColors(True)
        self.listView_BankList.setObjectName("listView_BankList")
        self.verticalLayout_3.addWidget(self.listView_BankList)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_FindBank = QtWidgets.QPushButton(self.widget)
        self.pushButton_FindBank.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_FindBank.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_FindBank.setFont(font)
        self.pushButton_FindBank.setObjectName("pushButton_FindBank")
        self.verticalLayout_2.addWidget(self.pushButton_FindBank)
        self.pushButton_SelAll = QtWidgets.QPushButton(self.widget)
        self.pushButton_SelAll.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_SelAll.setFont(font)
        self.pushButton_SelAll.setObjectName("pushButton_SelAll")
        self.verticalLayout_2.addWidget(self.pushButton_SelAll)
        self.pushButton_SelOne = QtWidgets.QPushButton(self.widget)
        self.pushButton_SelOne.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.pushButton_SelOne.setFont(font)
        self.pushButton_SelOne.setObjectName("pushButton_SelOne")
        self.verticalLayout_2.addWidget(self.pushButton_SelOne)
        self.pushButton_DelOne = QtWidgets.QPushButton(self.widget)
        self.pushButton_DelOne.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.pushButton_DelOne.setFont(font)
        self.pushButton_DelOne.setObjectName("pushButton_DelOne")
        self.verticalLayout_2.addWidget(self.pushButton_DelOne)
        self.pushButton_DelAll = QtWidgets.QPushButton(self.widget)
        self.pushButton_DelAll.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.pushButton_DelAll.setFont(font)
        self.pushButton_DelAll.setObjectName("pushButton_DelAll")
        self.verticalLayout_2.addWidget(self.pushButton_DelAll)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.listView_BankList_Sel = QtWidgets.QListView(self.widget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.listView_BankList_Sel.setFont(font)
        self.listView_BankList_Sel.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView_BankList_Sel.setAlternatingRowColors(True)
        self.listView_BankList_Sel.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listView_BankList_Sel.setObjectName("listView_BankList_Sel")
        self.horizontalLayout_5.addWidget(self.listView_BankList_Sel)
        self.widget1 = QtWidgets.QWidget(Dialog_ChangeFileName)
        self.widget1.setGeometry(QtCore.QRect(11, 11, 781, 202))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setMinimumSize(QtCore.QSize(88, 0))
        self.label_2.setMaximumSize(QtCore.QSize(88, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.LineEdit_Dlg_Filename = QtWidgets.QLineEdit(self.widget1)
        self.LineEdit_Dlg_Filename.setMinimumSize(QtCore.QSize(0, 30))
        self.LineEdit_Dlg_Filename.setObjectName("LineEdit_Dlg_Filename")
        self.horizontalLayout_2.addWidget(self.LineEdit_Dlg_Filename)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Label_3 = QtWidgets.QLabel(self.widget1)
        self.Label_3.setMinimumSize(QtCore.QSize(88, 0))
        self.Label_3.setMaximumSize(QtCore.QSize(88, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.Label_3.setFont(font)
        self.Label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_3.setObjectName("Label_3")
        self.horizontalLayout.addWidget(self.Label_3)
        self.comboBox_Dlg_What = QtWidgets.QComboBox(self.widget1)
        self.comboBox_Dlg_What.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.comboBox_Dlg_What.setFont(font)
        self.comboBox_Dlg_What.setObjectName("comboBox_Dlg_What")
        self.horizontalLayout.addWidget(self.comboBox_Dlg_What)
        self.Label_4 = QtWidgets.QLabel(self.widget1)
        self.Label_4.setMinimumSize(QtCore.QSize(88, 0))
        self.Label_4.setMaximumSize(QtCore.QSize(88, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.Label_4.setFont(font)
        self.Label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_4.setObjectName("Label_4")
        self.horizontalLayout.addWidget(self.Label_4)
        self.comboBox_Dlg_User = QtWidgets.QComboBox(self.widget1)
        self.comboBox_Dlg_User.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.comboBox_Dlg_User.setFont(font)
        self.comboBox_Dlg_User.setObjectName("comboBox_Dlg_User")
        self.horizontalLayout.addWidget(self.comboBox_Dlg_User)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(3, 3, 3, -1)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Label_5 = QtWidgets.QLabel(self.widget1)
        self.Label_5.setMinimumSize(QtCore.QSize(88, 0))
        self.Label_5.setMaximumSize(QtCore.QSize(88, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.Label_5.setFont(font)
        self.Label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_5.setObjectName("Label_5")
        self.horizontalLayout_4.addWidget(self.Label_5)
        self.LineEdit_Dlg_Who = QtWidgets.QLineEdit(self.widget1)
        self.LineEdit_Dlg_Who.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.LineEdit_Dlg_Who.setFont(font)
        self.LineEdit_Dlg_Who.setObjectName("LineEdit_Dlg_Who")
        self.horizontalLayout_4.addWidget(self.LineEdit_Dlg_Who)
        self.Label_6 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.Label_6.setFont(font)
        self.Label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_6.setObjectName("Label_6")
        self.horizontalLayout_4.addWidget(self.Label_6)
        self.LineEdit_Dlg_Pnum = QtWidgets.QLineEdit(self.widget1)
        self.LineEdit_Dlg_Pnum.setMinimumSize(QtCore.QSize(60, 30))
        self.LineEdit_Dlg_Pnum.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.LineEdit_Dlg_Pnum.setFont(font)
        self.LineEdit_Dlg_Pnum.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhEmailCharactersOnly)
        self.LineEdit_Dlg_Pnum.setObjectName("LineEdit_Dlg_Pnum")
        self.horizontalLayout_4.addWidget(self.LineEdit_Dlg_Pnum)
        self.Label_7 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.Label_7.setFont(font)
        self.Label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_7.setObjectName("Label_7")
        self.horizontalLayout_4.addWidget(self.Label_7)
        self.LineEdit_Dlg_Unum = QtWidgets.QLineEdit(self.widget1)
        self.LineEdit_Dlg_Unum.setMinimumSize(QtCore.QSize(60, 30))
        self.LineEdit_Dlg_Unum.setMaximumSize(QtCore.QSize(60, 16777215))
        self.LineEdit_Dlg_Unum.setSizeIncrement(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.LineEdit_Dlg_Unum.setFont(font)
        self.LineEdit_Dlg_Unum.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.LineEdit_Dlg_Unum.setObjectName("LineEdit_Dlg_Unum")
        self.horizontalLayout_4.addWidget(self.LineEdit_Dlg_Unum)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(3, 3, 3, -1)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setMinimumSize(QtCore.QSize(88, 69))
        self.label.setMaximumSize(QtCore.QSize(16777215, 69))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.textEdit_Dlg_Sms = QtWidgets.QTextEdit(self.widget1)
        self.textEdit_Dlg_Sms.setMinimumSize(QtCore.QSize(0, 69))
        self.textEdit_Dlg_Sms.setMaximumSize(QtCore.QSize(16777215, 69))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.textEdit_Dlg_Sms.setFont(font)
        self.textEdit_Dlg_Sms.setObjectName("textEdit_Dlg_Sms")
        self.horizontalLayout_3.addWidget(self.textEdit_Dlg_Sms)
        self.pushButton_Save = QtWidgets.QPushButton(self.widget1)
        self.pushButton_Save.setMinimumSize(QtCore.QSize(100, 69))
        self.pushButton_Save.setMaximumSize(QtCore.QSize(100, 69))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_Save.setFont(font)
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.horizontalLayout_3.addWidget(self.pushButton_Save)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog_ChangeFileName)
        self.pushButton_Save.clicked.connect(Dialog_ChangeFileName.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog_ChangeFileName)

    def retranslateUi(self, Dialog_ChangeFileName):
        _translate = QtCore.QCoreApplication.translate
        Dialog_ChangeFileName.setWindowTitle(_translate("Dialog_ChangeFileName", "查询文书更名入库"))
        self.pushButton_FindBank.setText(_translate("Dialog_ChangeFileName", "查   找"))
        self.pushButton_SelAll.setText(_translate("Dialog_ChangeFileName", ">>"))
        self.pushButton_SelOne.setText(_translate("Dialog_ChangeFileName", ">"))
        self.pushButton_DelOne.setText(_translate("Dialog_ChangeFileName", "<"))
        self.pushButton_DelAll.setText(_translate("Dialog_ChangeFileName", "<<"))
        self.label_2.setText(_translate("Dialog_ChangeFileName", "文件名称"))
        self.Label_3.setText(_translate("Dialog_ChangeFileName", "协查内容"))
        self.Label_4.setText(_translate("Dialog_ChangeFileName", "申请单位"))
        self.Label_5.setText(_translate("Dialog_ChangeFileName", "对象名称"))
        self.Label_6.setText(_translate("Dialog_ChangeFileName", "人  数"))
        self.Label_7.setText(_translate("Dialog_ChangeFileName", "单位数"))
        self.label.setText(_translate("Dialog_ChangeFileName", "短 消 息"))
        self.textEdit_Dlg_Sms.setToolTip(_translate("Dialog_ChangeFileName", "请输入短消息"))
        self.pushButton_Save.setText(_translate("Dialog_ChangeFileName", "确   定"))

        with open('userInfoSet.json', 'r',encoding='UTF-8') as f:  # 打开文件用于读
            data = json.load(f)
            f.close()
        i = 0
        for k,v in data["client"].items():
            self.comboBox_Dlg_What.addItem("")
            self.comboBox_Dlg_What.setItemText(i, _translate("Dialog_ChangeFileName", v[1]))
            i=i+1
        i = 0
        for  i  in range(len(data["customer"])):
            self.comboBox_Dlg_User.addItem("")
            self.comboBox_Dlg_User.setItemText(i, _translate("Dialog_ChangeFileName", data["customer"][i]))