# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginUI_user.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_Login(object):
    def setupUi(self, Dialog_Login):
        Dialog_Login.setObjectName("Dialog_Login")
        Dialog_Login.setWindowModality(QtCore.Qt.NonModal)
        Dialog_Login.resize(462, 696)
        Dialog_Login.setMinimumSize(QtCore.QSize(462, 696))
        Dialog_Login.setMaximumSize(QtCore.QSize(462, 696))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_Login.setWindowIcon(icon)
        Dialog_Login.setStyleSheet("")
        Dialog_Login.setModal(True)
        self.listWidget = QtWidgets.QListWidget(Dialog_Login)
        self.listWidget.setGeometry(QtCore.QRect(-670, 180, 256, 192))
        self.listWidget.setObjectName("listWidget")
        self.checkBox = QtWidgets.QCheckBox(Dialog_Login)
        self.checkBox.setGeometry(QtCore.QRect(180, 510, 161, 35))
        self.checkBox.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(11)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog_Login)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(130, 570, 195, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Login = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_Login.setMinimumSize(QtCore.QSize(0, 33))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.pushButton_Login.setFont(font)
        self.pushButton_Login.setObjectName("pushButton_Login")
        self.horizontalLayout.addWidget(self.pushButton_Login)
        self.pushButton_Set = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_Set.setMinimumSize(QtCore.QSize(0, 33))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.pushButton_Set.setFont(font)
        self.pushButton_Set.setObjectName("pushButton_Set")
        self.horizontalLayout.addWidget(self.pushButton_Set)
        self.layoutWidget = QtWidgets.QWidget(Dialog_Login)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 320, 301, 165))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setObjectName("gridLayout")
        self.Label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.Label.setFont(font)
        self.Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Label.setObjectName("Label")
        self.gridLayout.addWidget(self.Label, 0, 0, 1, 1)
        self.comboBox_Name = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_Name.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.comboBox_Name.setFont(font)
        self.comboBox_Name.setEditable(False)
        self.comboBox_Name.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comboBox_Name.setObjectName("comboBox_Name")
        self.comboBox_Name.addItem("")
        self.gridLayout.addWidget(self.comboBox_Name, 0, 1, 1, 1)
        self.Label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.Label_2.setFont(font)
        self.Label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_2.setObjectName("Label_2")
        self.gridLayout.addWidget(self.Label_2, 1, 0, 1, 1)
        self.LineEdit_Password = QtWidgets.QLineEdit(self.layoutWidget)
        self.LineEdit_Password.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.LineEdit_Password.setFont(font)
        self.LineEdit_Password.setObjectName("LineEdit_Password")
        self.gridLayout.addWidget(self.LineEdit_Password, 1, 1, 1, 1)
        self.Label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.Label_3.setFont(font)
        self.Label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_3.setObjectName("Label_3")
        self.gridLayout.addWidget(self.Label_3, 2, 0, 1, 1)
        self.LineEdit_ServerIP = QtWidgets.QLineEdit(self.layoutWidget)
        self.LineEdit_ServerIP.setMinimumSize(QtCore.QSize(0, 35))
        self.LineEdit_ServerIP.setObjectName("LineEdit_ServerIP")
        self.gridLayout.addWidget(self.LineEdit_ServerIP, 2, 1, 1, 1)
        self.Label_ServerPort = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.Label_ServerPort.setFont(font)
        self.Label_ServerPort.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_ServerPort.setObjectName("Label_ServerPort")
        self.gridLayout.addWidget(self.Label_ServerPort, 3, 0, 1, 1)
        self.LineEdit_ServerPort = QtWidgets.QLineEdit(self.layoutWidget)
        self.LineEdit_ServerPort.setMinimumSize(QtCore.QSize(0, 35))
        self.LineEdit_ServerPort.setObjectName("LineEdit_ServerPort")
        self.gridLayout.addWidget(self.LineEdit_ServerPort, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog_Login)
        self.label.setGeometry(QtCore.QRect(0, 0, 462, 696))
        self.label.setMinimumSize(QtCore.QSize(462, 696))
        self.label.setMaximumSize(QtCore.QSize(462, 696))
        self.label.setStyleSheet("background-image: url(:/pic/login.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.listWidget.raise_()
        self.checkBox.raise_()
        self.horizontalLayoutWidget.raise_()
        self.layoutWidget.raise_()

        self.retranslateUi(Dialog_Login)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Login)

    def retranslateUi(self, Dialog_Login):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Login.setWindowTitle(_translate("Dialog_Login", "欢迎"))
        self.checkBox.setText(_translate("Dialog_Login", "记住密码"))
        self.pushButton_Login.setText(_translate("Dialog_Login", "登  录"))
        self.pushButton_Set.setText(_translate("Dialog_Login", "设置"))
        self.Label.setText(_translate("Dialog_Login", "用      户"))
        self.comboBox_Name.setItemText(0, _translate("Dialog_Login", "纪委"))
        self.Label_2.setText(_translate("Dialog_Login", "密      码"))
        self.Label_3.setText(_translate("Dialog_Login", "服务器地址"))
        self.Label_ServerPort.setText(_translate("Dialog_Login", "服务器端口"))

import JW_rc
